[build-system]
requires = ["hatchling>=1.29.0", "version-pioneer>=0.0.16"]
build-backend = "hatchling.build"

[project]
name = "richer-prompt"
dynamic = ["version"]
description = "Interactive prompts with Rich"
authors = [{ name = "Gabriel Mello Silva", email = "msilva-gabriel@proton.me" }]
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = ["readchar>=4.0.0", "rich>=13.0.0"]

[dependency-groups]
dev = [
    "ipython>=9.10.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.3",
    "ty>=0.0.56",
    "version-pioneer>=0.0.16",
]
docs = [
    "sphinx>=8.2.3",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-copybutton>=0.5.2",
    "sphinx-inline-tabs>=2025.12.21.14",
    "furo>=2024.8.6",
]

[tool.hatch.version]
source = "version-pioneer"

[tool.hatch.build.hooks.version-pioneer]
# section is empty because we read config from `[tool.version-pioneer]` section.

[tool.version-pioneer]
versionscript = "src/richer_prompt/_version.py"
versionfile-sdist = "src/richer_prompt/_version.py"
versionfile-wheel = "richer_prompt/_version.py"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"

[tool.ruff.lint]
extend-select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "I",   # isort
    "SIM", # flake8-simplify
]
